### 회원가입
POST http://localhost:8080/api/members/signup
Content-Type: application/json

{
  "email" : "email@naver.com",
  "password" : "Qwerty1234!",
  "nickname" : "nickname",
  "gender" : "MALE",
  "age" : 23
}

### 로그인
POST http://localhost:8080/api/members/login
Content-Type: application/json

{
  "email" : "email@naver.com",
  "password" : "Qwerty1234!"
}