### 예산생성
POST http://localhost:8080/api/budgets
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "startDate": "2025-03-01",
  "endDate": "2025-04-22",
  "totalAmount": 600000
}


### 예산삭제
DELETE http://localhost:8080/api/budgets/5
Content-Type: application/json
Authorization: Bearer {{accessToken}}


### 예산조회
GET http://localhost:8080/api/budgets/3
Content-Type: application/json
Authorization: Bearer {{accessToken}}


### 활성화된 예산 조회
GET http://localhost:8080/api/budgets/active
Content-Type: application/json
Authorization: Bearer {{accessToken}}