### 카테고리생성(소비)
POST http://localhost:8080/api/category
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "categoryName": "동생용돈1",
  "type": "EXPENSE"
}


### 단일 카테고리 조회
GET http://localhost:8080/api/category/1
Content-Type: application/json
Authorization: Bearer {{accessToken}}