spring:
    application:
        name: piccount-BE

    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/piccount
        username: ${MYSQL_USER}
        password: ${MYSQL_PASSWORD}

    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        database-platform: org.hibernate.dialect.MySQLDialect
        properties:
            hibernate:
                format-sql: true
            highlight-sql: true
            use_sql_comments: true


