name: Mirror to GitLab

on:
  push:
    branches:
      - develop

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # 전체 커밋 히스토리 필요

      - name: Mirror to GitLab
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git remote add gitlab "https://oauth2:${{ secrets.GITLAB_TOKEN }}@${{ secrets.GITLAB_REPO }}"
          git push gitlab --all
          git push gitlab --tags


